---
title: "Fill the Gap"
author: "Otho Mantegazza"
date: 2017-05-26
summary: "Can Open Source Hardware help fill the gap and bring technology within reach for everybody?"
output:
  blogdown::html_page:
    fig_width: 6
---

Can **Open Source Hardware** help fill the gap and bring technology within
reach for everybody?

I am a biologist in academia. I am curious about how Open Source Hardware
can improve the way we do research and the way in which we distribute our
results and the technology that we produce.

# Definitions first

The [Open Source Hardware Association](https://www.oshwa.org) defines Open Source
Hardware as:

> "hardware whose design is made publicly available so that anyone can study, modify, distribute, make, and sell the design or hardware based on that design"  

Starting from the late 90s many engineers, passionate users, companies and
organization have tried to define standards for Open Source Hardware and to
advertise for it, they were probably inspired by the success of Open Source
Software.

# Lessons from Software

A couple of decades ago, the **Open Source** movement made a strong
statement on how the source code of commonly used software should be
available to everybody.

This was a matter of **fairness**. We deal with software constantly in our
life and it sounds reasonable that we know how that software works.

But this proved also **practical**. It fueled software development in the
last decades and the broad start-up environment that thrived around it.

It is worth mentioning that sharing the source code is good enough, but many
open source projects went further than that.
They provided **extensive and sometimes redundant documentation** on how to use
their product, on how to take
control of it and on how to modify any aspect of it.
Then, the community could redistribute the modified and improved products thanks to **permissive** and **copyleft** licenses.

The success of this model highlights the **benefits that
arise from a widespread and distributed access to knowledge** for everybody.


# In Universities and in biology

Through **synthetic biology**, open source hardware is already making its way to
biology and biotechnology.

I am trying to collect a [list of projects](https://othomantegazza.github.io/open-hardware-bio.html)
that are related to Open Source Hardware and Biology and looking at homemade
centrifuges, open PCR machines, microfluidics devices, I have the impression that
this way of doing things is rapidly growing.

As stated above, I am interested in its role and impact on academic research,
specifically in the fields of biology and plant science. (and eventually I would
like to use those tools myself for my research :) )

## Redistributing knowledge

By definition **Open Source** software and hardware are about how we distribute
knowledge.

A model that stresses the importance of **openly
redistributing knowledge as widely as possible** and of **facilitating
re-use of that knowledge / technology** seems only reasonable for
**Universities**, which indeed have the **role in society** of generating knowledge and making it available.

What I am also really curious about is to figure out if Open Source Hardware could also improve the way we do research and not exclusively the way we distribute it.


## Making research easier for academics

In my (small) experience as academic researcher, one of the main issues that
we, young biologists, face is that we are mostly **end users** of very
expensive and sophisticated machines and technologies.

In this way, we can perform very complex tasks and experiments with relatively
little effort, but we also partially lose control on what we are doing.

In details, this might cause that:

- Laboratories depend more and more on **high level funding**;
  low funded labs get left behind, which could be an issue on the global scale.
  Since the end user model is productive in the short term, laboratories that try
  different approaches, again, might get left behind,
- This relegates researchers to a **performer / technical** position, in
  which they are required to perform a high number of repetitive tasks with
  little chances to modify the workflows of their experiments. If researchers would gain
  more control on the technology that they use, they might have bigger chances of optimizing their experimental workflows. For example, making them simpler, less polluting and more accessible.
- This might have an effect also on **reproducibility** and distributed
  collaborative development, simply because the chances of making
  reproducible something on which you have no control are small.

Open Source Hardware might have a role solving those issues but since only few laboratories implement open hardware methodically I can't be sure about it.

But open source software already helped biologist a lot, especially in
bioinformatics and in data analysis through impressive frameworks such as,
for example, [BioConductor](http://bioconductor.org/). This raises hopes that
Open Source Hardware could have a similar impact for wet lab scientists.

Of course the issue of a [funding system that might encourage bad scientific behavior](https://simplystatistics.org/2016/02/16/when-it-comes-to-science-its-the-economy-stupid/)
remains, but Open Hardware could be a move in the
right direction and improve the life of young biologists.

# An Impact on farming?

As academic researcher I often wonder what will be the impact of my research.

I am specialized in genetics and plant biology, so my research might have impact on
agriculture and farming, especially in breeding new crop varieties.

If we, plant biologists, would apply Open Source Hardware systematically, we might, for
example, improve farming by **lowering the costs** necessary to access technologies such
as plant breeding.

So, can **Academic Research improve its impact**, down the
line, on farming by adopting an **open knowledge / open source software and
hardware model**? And also, could it help shift the role of a farmer from **end user** to **user/developer**?

[Some organizations](http://greenwave.org/) are already investing on this
model. I am moving a little bit outside of my field of expertise right here,
so I might not be the best person to answer those questions; but as always,
the success of Open Source Software raises hope that yes, this can happen.

---

*Thanks to Silvia, Leone and Alessandro for the help and the ideas.*
